name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create .env file
      run: |
        echo "HF_API_KEY=${{ secrets.HF_API_KEY }}" > .env
        echo "aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" >> .env
        echo "aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" >> .env
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/api:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/api:${{ github.sha }}
